version: '1.0.{build}'
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - pwsh: git config --global core.autocrlf true
  - pwsh: git config --global core.safecrlf false
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - pwsh: dotnet --version
  # Display minimal restore text
build_script:
  # Build scripts.
  - pwsh: .\build\build.ps1 -Configuration Release
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # run the unit tests.
on_finish :
  # any cleaup in here
deploy_script:
